#!/bin/bash

# Script de verificación para módulos Tratamiento y Patologia_Tratamiento
# Ejecutar dentro del contenedor Docker

echo "🔍 Verificando implementación de módulos..."
echo ""

# Colores
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Función para verificar archivos
check_file() {
    if [ -f "$1" ]; then
        echo -e "${GREEN}✓${NC} $1"
        return 0
    else
        echo -e "${RED}✗${NC} $1 - NO ENCONTRADO"
        return 1
    fi
}

echo "📁 Verificando archivos del módulo Tratamiento..."
check_file "app/modules/tratamiento/entities/tratamiento_entity.py"
check_file "app/modules/tratamiento/schemas/tratamiento_schema.py"
check_file "app/modules/tratamiento/interfaces/tratamiento_interfaces.py"
check_file "app/modules/tratamiento/repositories/tratamiento_repository.py"
check_file "app/modules/tratamiento/services/tratamiento_service.py"
check_file "app/modules/tratamiento/controllers/tratamiento_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Patologia_Tratamiento..."
check_file "app/modules/patologia_tratamiento/entities/patologia_tratamiento_entity.py"
check_file "app/modules/patologia_tratamiento/schemas/patologia_tratamiento_schema.py"
check_file "app/modules/patologia_tratamiento/interfaces/patologia_tratamiento_interfaces.py"
check_file "app/modules/patologia_tratamiento/repositories/patologia_tratamiento_repository.py"
check_file "app/modules/patologia_tratamiento/services/patologia_tratamiento_service.py"
check_file "app/modules/patologia_tratamiento/controllers/patologia_tratamiento_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Encargado..."
check_file "app/modules/encargado/entities/encargado_entity.py"
check_file "app/modules/encargado/schemas/encargado_schema.py"
check_file "app/modules/encargado/interfaces/encargado_interfaces.py"
check_file "app/modules/encargado/repositories/encargado_repository.py"
check_file "app/modules/encargado/services/encargado_service.py"
check_file "app/modules/encargado/controllers/encargado_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Diagnóstico..."
check_file "app/modules/diagnostico/entities/diagnostico_entity.py"
check_file "app/modules/diagnostico/schemas/diagnostico_schema.py"
check_file "app/modules/diagnostico/interfaces/diagnostico_interfaces.py"
check_file "app/modules/diagnostico/repositories/diagnostico_repository.py"
check_file "app/modules/diagnostico/services/diagnostico_service.py"
check_file "app/modules/diagnostico/controllers/diagnostico_controller.py"

echo ""
echo "📁 Verificando archivos del módulo CIE10..."
check_file "app/modules/cie10/entities/cie10_entity.py"
check_file "app/modules/cie10/schemas/cie10_schema.py"
check_file "app/modules/cie10/repositories/cie10_repository.py"
check_file "app/modules/cie10/services/cie10_service.py"
check_file "app/modules/cie10/controllers/cie10_controller.py"

echo ""
echo "📁 Verificando archivos del módulo GES..."
check_file "app/modules/ges/entities/ges_entity.py"
check_file "app/modules/ges/schemas/ges_schema.py"
check_file "app/modules/ges/repositories/ges_repository.py"
check_file "app/modules/ges/services/ges_service.py"
check_file "app/modules/ges/controllers/ges_controller.py"

echo ""
echo "📁 Verificando archivos del módulo CIE10-GES..."
check_file "app/modules/cie10_ges/entities/cie10_ges_entity.py"
check_file "app/modules/cie10_ges/schemas/cie10_ges_schema.py"
check_file "app/modules/cie10_ges/repositories/cie10_ges_repository.py"
check_file "app/modules/cie10_ges/services/cie10_ges_service.py"
check_file "app/modules/cie10_ges/controllers/cie10_ges_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Tipo Examen..."
check_file "app/modules/tipo_examen/entities/tipo_examen_entity.py"
check_file "app/modules/tipo_examen/schemas/tipo_examen_schema.py"
check_file "app/modules/tipo_examen/repositories/tipo_examen_repository.py"
check_file "app/modules/tipo_examen/services/tipo_examen_service.py"
check_file "app/modules/tipo_examen/controllers/tipo_examen_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Instalación..."
check_file "app/modules/instalacion/entities/instalacion_entity.py"
check_file "app/modules/instalacion/schemas/instalacion_schema.py"
check_file "app/modules/instalacion/repositories/instalacion_repository.py"
check_file "app/modules/instalacion/services/instalacion_service.py"
check_file "app/modules/instalacion/controllers/instalacion_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Orden Examen..."
check_file "app/modules/orden_examen/entities/orden_examen_entity.py"
check_file "app/modules/orden_examen/schemas/orden_examen_schema.py"
check_file "app/modules/orden_examen/repositories/orden_examen_repository.py"
check_file "app/modules/orden_examen/services/orden_examen_service.py"
check_file "app/modules/orden_examen/controllers/orden_examen_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Examen..."
check_file "app/modules/examen/entities/examen_entity.py"
check_file "app/modules/examen/schemas/examen_schema.py"
check_file "app/modules/examen/repositories/examen_repository.py"
check_file "app/modules/examen/services/examen_service.py"
check_file "app/modules/examen/controllers/examen_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Orden Hospitalización..."
check_file "app/modules/orden_hospitalizacion/entities/orden_hospitalizacion_entity.py"
check_file "app/modules/orden_hospitalizacion/schemas/orden_hospitalizacion_schema.py"
check_file "app/modules/orden_hospitalizacion/repositories/orden_hospitalizacion_repository.py"
check_file "app/modules/orden_hospitalizacion/services/orden_hospitalizacion_service.py"
check_file "app/modules/orden_hospitalizacion/controllers/orden_hospitalizacion_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Hospitalización..."
check_file "app/modules/hospitalizacion/entities/hospitalizacion_entity.py"
check_file "app/modules/hospitalizacion/schemas/hospitalizacion_schema.py"
check_file "app/modules/hospitalizacion/repositories/hospitalizacion_repository.py"
check_file "app/modules/hospitalizacion/services/hospitalizacion_service.py"
check_file "app/modules/hospitalizacion/controllers/hospitalizacion_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Tratamiento Hospitalización..."
check_file "app/modules/tratamiento_hospitalizacion/entities/tratamiento_hospitalizacion_entity.py"
check_file "app/modules/tratamiento_hospitalizacion/schemas/tratamiento_hospitalizacion_schema.py"
check_file "app/modules/tratamiento_hospitalizacion/repositories/tratamiento_hospitalizacion_repository.py"
check_file "app/modules/tratamiento_hospitalizacion/services/tratamiento_hospitalizacion_service.py"
check_file "app/modules/tratamiento_hospitalizacion/controllers/tratamiento_hospitalizacion_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Medicamento Hospitalización..."
check_file "app/modules/medicamento_hospitalizacion/entities/medicamento_hospitalizacion_entity.py"
check_file "app/modules/medicamento_hospitalizacion/schemas/medicamento_hospitalizacion_schema.py"
check_file "app/modules/medicamento_hospitalizacion/repositories/medicamento_hospitalizacion_repository.py"
check_file "app/modules/medicamento_hospitalizacion/services/medicamento_hospitalizacion_service.py"
check_file "app/modules/medicamento_hospitalizacion/controllers/medicamento_hospitalizacion_controller.py"

echo ""
echo "📁 Verificando archivos del módulo Estado..."
check_file "app/modules/estado/entities/estado_entity.py"
check_file "app/modules/estado/schemas/estado_schema.py"
check_file "app/modules/estado/repositories/estado_repository.py"
check_file "app/modules/estado/services/estado_service.py"
check_file "app/modules/estado/controllers/estado_controller.py"

echo ""
echo "🔧 Verificando sintaxis Python..."
python -m py_compile app/modules/tratamiento/entities/tratamiento_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Tratamiento entity - OK" || echo -e "${RED}✗${NC} Tratamiento entity - ERROR"
python -m py_compile app/modules/patologia_tratamiento/entities/patologia_tratamiento_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} PatologiaTratamiento entity - OK" || echo -e "${RED}✗${NC} PatologiaTratamiento entity - ERROR"
python -m py_compile app/modules/encargado/entities/encargado_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Encargado entity - OK" || echo -e "${RED}✗${NC} Encargado entity - ERROR"
python -m py_compile app/modules/diagnostico/entities/diagnostico_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Diagnostico entity - OK" || echo -e "${RED}✗${NC} Diagnostico entity - ERROR"
python -m py_compile app/modules/cie10/entities/cie10_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Cie10 entity - OK" || echo -e "${RED}✗${NC} Cie10 entity - ERROR"
python -m py_compile app/modules/ges/entities/ges_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Ges entity - OK" || echo -e "${RED}✗${NC} Ges entity - ERROR"
python -m py_compile app/modules/tipo_examen/entities/tipo_examen_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} TipoExamen entity - OK" || echo -e "${RED}✗${NC} TipoExamen entity - ERROR"
python -m py_compile app/modules/instalacion/entities/instalacion_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Instalacion entity - OK" || echo -e "${RED}✗${NC} Instalacion entity - ERROR"
python -m py_compile app/modules/orden_examen/entities/orden_examen_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} OrdenExamen entity - OK" || echo -e "${RED}✗${NC} OrdenExamen entity - ERROR"
python -m py_compile app/modules/examen/entities/examen_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Examen entity - OK" || echo -e "${RED}✗${NC} Examen entity - ERROR"
python -m py_compile app/modules/orden_hospitalizacion/entities/orden_hospitalizacion_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} OrdenHospitalizacion entity - OK" || echo -e "${RED}✗${NC} OrdenHospitalizacion entity - ERROR"
python -m py_compile app/modules/hospitalizacion/entities/hospitalizacion_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Hospitalizacion entity - OK" || echo -e "${RED}✗${NC} Hospitalizacion entity - ERROR"
python -m py_compile app/modules/tratamiento_hospitalizacion/entities/tratamiento_hospitalizacion_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} TratamientoHospitalizacion entity - OK" || echo -e "${RED}✗${NC} TratamientoHospitalizacion entity - ERROR"
python -m py_compile app/modules/medicamento_hospitalizacion/entities/medicamento_hospitalizacion_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} MedicamentoHospitalizacion entity - OK" || echo -e "${RED}✗${NC} MedicamentoHospitalizacion entity - ERROR"
python -m py_compile app/modules/estado/entities/estado_entity.py 2>/dev/null && echo -e "${GREEN}✓${NC} Estado entity - OK" || echo -e "${RED}✗${NC} Estado entity - ERROR"

echo ""
echo "📊 Resumen de endpoints disponibles:"
echo ""
echo -e "${YELLOW}Tratamiento:${NC}"
echo "  GET    /tratamiento/"
echo "  POST   /tratamiento/"
echo "  GET    /tratamiento/{id}"
echo "  PATCH  /tratamiento/{id}"
echo "  DELETE /tratamiento/{id}"
echo ""
echo -e "${YELLOW}Patologia-Tratamiento:${NC}"
echo "  GET    /patologia_tratamiento/"
echo "  POST   /patologia_tratamiento/"
echo "  DELETE /patologia_tratamiento/{id_patologia}/{id_tratamiento}"
echo "  GET    /patologia_tratamiento/patologia/{id}/tratamientos"
echo "  GET    /patologia_tratamiento/tratamiento/{id}/patologias"
echo ""
echo -e "${YELLOW}Encargado:${NC}"
echo "  GET    /encargado/"
echo "  POST   /encargado/"
echo "  GET    /encargado/{id}"
echo "  PATCH  /encargado/{id}"
echo "  DELETE /encargado/{id}"
echo "  GET    /encargado/cargo/{cargo}"
echo "  GET    /encargado/activos/lista"
echo ""
echo -e "${YELLOW}Diagnóstico:${NC}"
echo "  GET    /diagnostico/"
echo "  POST   /diagnostico/"
echo "  GET    /diagnostico/{id}"
echo "  PATCH  /diagnostico/{id}"
echo "  DELETE /diagnostico/{id}"
echo "  GET    /diagnostico/consulta/{id_consulta}"
echo "  GET    /diagnostico/tipo/{tipo}"
echo "  GET    /diagnostico/cobertura/ges"
echo ""
echo -e "${YELLOW}CIE-10:${NC}"
echo "  GET    /cie10/"
echo "  GET    /cie10/search?q={term}"
echo "  POST   /cie10/"
echo "  GET    /cie10/{id}"
echo "  PATCH  /cie10/{id}"
echo "  DELETE /cie10/{id}"
echo ""
echo -e "${YELLOW}GES:${NC}"
echo "  GET    /ges/"
echo "  GET    /ges/search?q={term}"
echo "  POST   /ges/"
echo "  GET    /ges/{id}"
echo "  PATCH  /ges/{id}"
echo "  DELETE /ges/{id}"
echo ""
echo -e "${YELLOW}CIE10-GES:${NC}"
echo "  GET    /cie10_ges/"
echo "  POST   /cie10_ges/"
echo "  DELETE /cie10_ges/{id_cie10}/{id_ges}"
echo "  GET    /cie10_ges/cie10/{id}/ges"
echo "  GET    /cie10_ges/ges/{id}/cie10"
echo ""
echo -e "${YELLOW}Exámenes:${NC}"
echo "  GET    /tipo_examen/"
echo "  GET    /instalacion/"
echo "  GET    /orden_examen/"
echo "  GET    /examen/"
echo ""
echo -e "${YELLOW}Hospitalización:${NC}"
echo "  GET    /orden_hospitalizacion/"
echo "  GET    /hospitalizacion/"
echo "  GET    /tratamiento_hospitalizacion/"
echo "  GET    /medicamento_hospitalizacion/"
echo ""
echo -e "${YELLOW}Estado:${NC}"
echo "  GET    /estado/"
echo "  GET    /estado/{id}"




echo ""
echo -e "${YELLOW}Sesión (actualizado):${NC}"
echo "  POST   /sesion/  (ahora acepta id_tratamiento opcional)"
echo ""
echo "✅ Verificación completada!"
echo ""
echo "💡 Para probar los endpoints, ejecuta:"
echo "   docker compose logs -f app    # Ver logs"
echo "   curl http://localhost:8000/docs  # Documentación interactiva"
